apiVersion: v1
kind: ConfigMap
metadata:
  name: metricscollector-template
  namespace: katib
data:
  defaultMetricsCollectorTemplate.yaml : |-
    apiVersion: batch/v1beta1
    kind: CronJob
    metadata:
      name: {{.WorkerId}}
      namespace: {{.NameSpace}}
    spec:
      schedule: "*/1 * * * *"
      jobTemplate:
        spec:
          template:
            spec:
              {{- if .ServiceAccount}}
              serviceAccountName: {{.ServiceAccount}}
              {{- else}}
              serviceAccountName: metrics-collector
              {{- end}}
              containers:
              - name: {{.WorkerId}}
                image: katib/metrics-collector
                args:
                - "./metricscollector"
                - "-s"
                - "{{.StudyId}}"
                - "-w"
                - "{{.WorkerId}}"
                - "-n"
                - "{{.NameSpace}}"
              restartPolicy: Never
