---
apiVersion: config.kubeflow.org/v1beta1
kind: KatibConfig
init:
  controller:
    webhookPort: 8443
    trialResources:
      - Job.v1.batch
      - TFJob.v1.kubeflow.org
      - PyTorchJob.v1.kubeflow.org
      - MPIJob.v1.kubeflow.org
      - XGBoostJob.v1.kubeflow.org
      - MXJob.v1.kubeflow.org
runtime:
  metricsCollectors:
    - kind: StdOut
      image: docker.io/kubeflowkatib/file-metrics-collector:$(KATIB_VERSION)
    - kind: File
      image: docker.io/kubeflowkatib/file-metrics-collector:$(KATIB_VERSION)
    - kind: TensorFlowEvent
      image: docker.io/kubeflowkatib/tfevent-metrics-collector:$(KATIB_VERSION)
      resources:
        limits:
          memory: 1Gi
  suggestions:
    - algorithmName: random
      image: docker.io/kubeflowkatib/suggestion-hyperopt:$(KATIB_VERSION)
    - algorithmName: tpe
      image: docker.io/kubeflowkatib/suggestion-hyperopt:$(KATIB_VERSION)
    - algorithmName: grid
      image: docker.io/kubeflowkatib/suggestion-optuna:$(KATIB_VERSION)
    - algorithmName: hyperband
      image: docker.io/kubeflowkatib/suggestion-hyperband:$(KATIB_VERSION)
    - algorithmName: bayesianoptimization
      image: docker.io/kubeflowkatib/suggestion-skopt:$(KATIB_VERSION)
    - algorithmName: cmaes
      image: docker.io/kubeflowkatib/suggestion-goptuna:$(KATIB_VERSION)
    - algorithmName: sobol
      image: docker.io/kubeflowkatib/suggestion-goptuna:$(KATIB_VERSION)
    - algorithmName: multivariate-tpe
      image: docker.io/kubeflowkatib/suggestion-optuna:$(KATIB_VERSION)
    - algorithmName: enas
      image: docker.io/kubeflowkatib/suggestion-enas:$(KATIB_VERSION)
      resources:
        limits:
          memory: 200Mi
    - algorithmName: darts
      image: docker.io/kubeflowkatib/suggestion-darts:$(KATIB_VERSION)
    - algorithmName: pbt
      image: docker.io/kubeflowkatib/suggestion-pbt:$(KATIB_VERSION)
      persistentVolumeClaimSpec:
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 5Gi
  earlyStoppings:
    - algorithmName: medianstop
      image: docker.io/kubeflowkatib/earlystopping-medianstop:$(KATIB_VERSION)
