apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
  # Namespace.
  - ../../components/namespace.yaml
  # Katib controller.
  - ../../components/controller/controller.yaml
  - ../../components/controller/service.yaml
  - ../../components/controller/rbac.yaml
  - ../../components/controller/katib-config.yaml
  - ../../components/controller/trial-templates.yaml
  # Katib CRDs.
  - ../../components/crd/experiment.yaml
  - ../../components/crd/suggestion.yaml
  - ../../components/crd/trial.yaml
  # Katib DB manager.
  - ../../components/db-manager/db-manager.yaml
  - ../../components/db-manager/service.yaml
  # Katib UI.
  - ../../components/ui/ui.yaml
  - ../../components/ui/service.yaml
  - ../../components/ui/rbac.yaml
  # Katib webhooks.
  - ../../components/webhook/cert-generator.yaml
  - ../../components/webhook/rbac.yaml
  - ../../components/webhook/webhooks.yaml
patchesStrategicMerge:
  - db-manager-patch.yaml
# Modify katib-mysql-secrets with parameters for the DB.
secretGenerator:
  - name: katib-mysql-secrets
    envs:
      - secrets.env
