apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
  - ../katib-cert-manager
  # Kubeflow Katib components.
  - kubeflow-katib-roles.yaml
  - ui-virtual-service.yaml
images:
  - name: docker.io/kubeflowkatib/katib-controller
    newName: docker.io/kubeflowkatib/katib-controller
    newTag: latest
  - name: docker.io/kubeflowkatib/katib-db-manager
    newName: docker.io/kubeflowkatib/katib-db-manager
    newTag: latest
  - name: docker.io/kubeflowkatib/katib-ui
    newName: docker.io/kubeflowkatib/katib-ui
    newTag: latest
patchesStrategicMerge:
  - patches/remove-pv-patch.yaml
  - |-
    apiVersion: v1
    kind: Namespace
    metadata:
      name: kubeflow
    $patch: delete
patchesJson6902:
  - path: patches/mysql-pvc.yaml
    target:
      version: v1
      name: katib-mysql
      kind: PersistentVolumeClaim
      namespace: kubeflow
vars:
- fieldref:
    fieldPath: metadata.namespace
  name: KATIB_UI_NAMESPACE
  objref:
    apiVersion: apps/v1
    kind: Deployment
    name: katib-ui

commonLabels:
  app.kubernetes.io/component: katib
configurations:
  - params.yaml
