apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
  # Katib controller.
  - ../../components/controller/
  # Katib CRDs.
  - ../../components/crd/
  # Katib DB manager.
  - ../../components/db-manager/
  # Katib DB mysql.
  - ../../components/mysql/
  # Katib UI.
  - ../../components/ui/
  # Katib webhooks.
  - ../../components/webhook/
  # Kubeflow Katib components.
  - kubeflow-katib-roles.yaml
  - ui-virtual-service.yaml
images:
  - name: docker.io/kubeflowkatib/katib-controller
    newTag: v0.11.0
    newName: docker.io/kubeflowkatib/katib-controller
  - name: docker.io/kubeflowkatib/katib-db-manager
    newTag: v0.11.0
    newName: docker.io/kubeflowkatib/katib-db-manager
  - name: docker.io/kubeflowkatib/katib-ui
    newTag: v0.11.0
    newName: docker.io/kubeflowkatib/katib-ui
  - name: docker.io/kubeflowkatib/cert-generator
    newTag: v0.11.0
    newName: docker.io/kubeflowkatib/cert-generator

patchesStrategicMerge:
  - katib-config-patch.yaml
  - remove-pv-patch.yaml

patchesJson6902:
  - path: patches/mysql-pvc.yaml
    target:
      version: v1
      name: katib-mysql
      kind: PersistentVolumeClaim
      namespace: kubeflow

vars:
- fieldref:
    fieldPath: metadata.namespace
  name: KATIB_UI_NAMESPACE
  objref:
    apiVersion: apps/v1
    kind: Deployment
    name: katib-ui

commonLabels:
  app.kubernetes.io/component: katib
configurations:
  - params.yaml
