language: go

go:
  - "1.10"
  - "1.11"
  - "1.12"

go_import_path: github.com/kubeflow/katib

install:
  - curl -L -O "https://github.com/kubernetes-sigs/kubebuilder/releases/download/v${version}/kubebuilder_${version}_${os}_${arch}.tar.gz"
  - # extract the archive
  - tar -zxvf kubebuilder_${version}_${os}_${arch}.tar.gz
  - mv kubebuilder_${version}_${os}_${arch} /usr/local/kubebuilder
  - export PATH=$PATH:/usr/local/kubebuilder/bin
  # get coveralls.io support
  - go get github.com/mattn/goveralls

script:
  - make test
  - goveralls -coverprofile=coverage.out
