# This file configures the workflows to trigger in our Prow jobs.
# see kubeflow/testing/py/run_e2e_workflow.py
workflows:
  - app_dir: kubeflow/katib/test/workflows
    component: workflows-v1alpha1
    name: e2e-v1alpha1
    job_types:
      - presubmit
    include_dirs:
    - pkg/*
    - cmd/*
    - test/*
    params:
      registry: "gcr.io/kubeflow-ci"
  # The postsubmit run publishes the docker images to gcr.io/kubeflow-images-public      
  - app_dir: kubeflow/katib/test/workflows
    component: workflows-v1alpha1
    name: e2e-v1alpha1-release
    job_types:      
      - postsubmit
    include_dirs:
    - pkg/*
    - cmd/*
    - test/*
    params:
      registry: "gcr.io/kubeflow-images-public"
  - app_dir: kubeflow/katib/test/workflows
    component: workflows-v1alpha2
    name: e2e-v1alpha2
    job_types:
      - presubmit
    include_dirs:
    - pkg/*
    - cmd/*
    - test/*
    params:
      registry: "gcr.io/kubeflow-ci"
  - app_dir: kubeflow/katib/test/workflows
    component: workflows-v1alpha2
    name: e2e-v1alpha2-release
    job_types:
      - postsubmit
    include_dirs:
    - pkg/*
    - cmd/*
    - test/*
    params:
      registry: "gcr.io/kubeflow-images-public"
