# This file configures the workflows to trigger in our Prow jobs.
# see kubeflow/testing/py/run_e2e_workflow.py
workflows:
  - app_dir: kubeflow/katib/test/workflows
    component: workflows-v1alpha1
    name: e2e-v1alpha1
    job_types:
      - presubmit
    include_dirs:
    - pkg/api/operators/*
    - pkg/api/health/*
    - pkg/api/v1alpha1/*
    - pkg/common/v1alpha1/*
    - pkg/controller/v1alpha1/*
    - pkg/db/v1alpha1/*
    - pkg/earlystopping/v1alpha1/*
    - pkg/manager/v1alpha1/*
    - pkg/manager/modelstore/*
    - pkg/suggestion/v1alpha1/*
    - pkg/ui/*
    - cmd/earlystopping/*
    - cmd/katib-controller/v1alpha1/*
    - cmd/katib-controller/Dockerfile
    - cmd/manager/v1alpha1/*
    - cmd/manager/Dockerfile
    - cmd/manager-rest/v1alpha1/*
    - cmd/manager-rest/Dockerfile
    - cmd/metricscollector/v1alpha1/*
    - cmd/metricscollector/Dockerfile
    - cmd/suggestion/*
    - cmd/tfevent-metricscollector/v1alpha1/*
    - cmd/tfevent-metricscollector/Dockerfile
    - cmd/ui/*
    - pkg/util/v1alpha1/*
    - test/e2e/v1alpha1/*
    - test/scripts/v1alpha1/*
    - test/workflows/*
    params:
      registry: "gcr.io/kubeflow-ci"
  # The postsubmit run publishes the docker images to gcr.io/kubeflow-images-public      
  - app_dir: kubeflow/katib/test/workflows
    component: workflows-v1alpha1
    name: e2e-v1alpha1-release
    job_types:      
      - postsubmit
    include_dirs:
    - pkg/api/operators/*
    - pkg/api/health/*
    - pkg/api/v1alpha1/*
    - pkg/common/v1alpha1/*
    - pkg/controller/v1alpha1/*
    - pkg/db/v1alpha1/*
    - pkg/earlystopping/v1alpha1/*
    - pkg/manager/v1alpha1/*
    - pkg/manager/modelstore/*
    - pkg/suggestion/v1alpha1/*
    - pkg/ui/*
    - cmd/earlystopping/*
    - cmd/katib-controller/v1alpha1/*
    - cmd/katib-controller/Dockerfile
    - cmd/manager/v1alpha1/*
    - cmd/manager/Dockerfile
    - cmd/manager-rest/v1alpha1/*
    - cmd/manager-rest/Dockerfile
    - cmd/metricscollector/v1alpha1/*
    - cmd/metricscollector/Dockerfile
    - cmd/suggestion/*
    - cmd/tfevent-metricscollector/v1alpha1/*
    - cmd/tfevent-metricscollector/Dockerfile
    - cmd/ui/*
    - pkg/util/v1alpha1/*
    - test/e2e/v1alpha1/*
    - test/scripts/v1alpha1/*
    - test/workflows/*
    params:
      registry: "gcr.io/kubeflow-images-public"
  - app_dir: kubeflow/katib/test/workflows
    component: workflows-v1alpha2
    name: e2e-v1alpha2
    job_types:
      - presubmit
    include_dirs:
    - pkg/api/operators/*
    - pkg/api/health/*
    - pkg/api/v1alpha2/*
    - pkg/common/v1alpha2/*
    - pkg/controller/v1alpha2/*
    - pkg/db/v1alpha2/*
    - pkg/earlystopping/v1alpha2/*
    - pkg/manager/v1alpha2/*
    - pkg/manager/modelstore/*
    - pkg/suggestion/v1alpha2/*
    - pkg/ui/*
    - cmd/earlystopping/*
    - cmd/katib-controller/v1alpha2/*
    - cmd/katib-controller/Dockerfile
    - cmd/manager/v1alpha2/*
    - cmd/manager/Dockerfile
    - cmd/manager-rest/v1alpha2/*
    - cmd/manager-rest/Dockerfile
    - cmd/metricscollector/v1alpha2/*
    - cmd/metricscollector/Dockerfile
    - cmd/suggestion/*
    - cmd/tfevent-metricscollector/v1alpha2/*
    - cmd/tfevent-metricscollector/Dockerfile
    - cmd/ui/*
    - pkg/util/v1alpha2/*
    - test/e2e/v1alpha2/*
    - test/scripts/v1alpha2/*
    - test/workflows/*
    params:
      registry: "gcr.io/kubeflow-ci"
  - app_dir: kubeflow/katib/test/workflows
    component: workflows-v1alpha2
    name: e2e-v1alpha2-release
    job_types:
      - postsubmit
    include_dirs:
    - pkg/api/operators/*
    - pkg/api/health/*
    - pkg/api/v1alpha2/*
    - pkg/common/v1alpha2/*
    - pkg/controller/v1alpha2/*
    - pkg/db/v1alpha2/*
    - pkg/earlystopping/v1alpha2/*
    - pkg/manager/v1alpha2/*
    - pkg/manager/modelstore/*
    - pkg/suggestion/v1alpha2/*
    - pkg/ui/*
    - cmd/earlystopping/*
    - cmd/katib-controller/v1alpha2/*
    - cmd/katib-controller/Dockerfile
    - cmd/manager/v1alpha2/*
    - cmd/manager/Dockerfile
    - cmd/manager-rest/v1alpha2/*
    - cmd/manager-rest/Dockerfile
    - cmd/metricscollector/v1alpha2/*
    - cmd/metricscollector/Dockerfile
    - cmd/suggestion/*
    - cmd/tfevent-metricscollector/v1alpha2/*
    - cmd/tfevent-metricscollector/Dockerfile
    - cmd/ui/*
    - pkg/util/v1alpha2/*
    - test/e2e/v1alpha2/*
    - test/scripts/v1alpha2/*
    - test/workflows/*
    params:
      registry: "gcr.io/kubeflow-images-public"
