# This file configures the workflows to trigger in our Prow jobs.
# see kubeflow/testing/py/run_e2e_workflow.py
workflows:
  - app_dir: kubeflow/katib/test/workflows
    component: workflows-v1alpha1
    name: e2e-v1alpha1
    job_types:
      - presubmit
    include_dirs:
    - pkg/api/operators/apis/studyjob/*
    - pkg/api/operators/apis/*.go
    - pkg/api/health/*
    - pkg/api/v1alpha1/*
    - pkg/common/v1alpha1/*
    - pkg/controller/v1alpha1/*
    - pkg/db/v1alpha1/*
    - pkg/earlystopping/v1alpha1/*
    - pkg/manager/v1alpha1/*
    - pkg/manager/modelstore/*
    - pkg/suggestion/v1alpha1/*
    - pkg/ui/v1alpha1/*
    - cmd/earlystopping/medianstopping/v1alpha1/*
    - cmd/katib-controller/v1alpha1/*
    - cmd/manager/v1alpha1/*
    - cmd/manager-rest/v1alpha1/*
    - cmd/metricscollector/v1alpha1/*
    - cmd/suggestion/bayesianoptimization/v1alpha1/*
    - cmd/suggestion/grid/v1alpha1/*
    - cmd/suggestion/hyperband/v1alpha1/*
    - cmd/suggestion/nasenvelopenet/v1alpha1/*
    - cmd/suggestion/nasrl/v1alpha1/*
    - cmd/suggestion/random/v1alpha1/*
    - cmd/tfevent-metricscollector/v1alpha1/*
    - cmd/ui/v1alpha1/*
    - pkg/util/v1alpha1/*
    - test/e2e/v1alpha1/*
    - test/scripts/v1alpha1/*
    - test/workflows/*
    - manifests/v1alpha1/*
    - scripts/v1alpha1/*
    - vendor/*
    params:
      registry: "gcr.io/kubeflow-ci"
  # The postsubmit run publishes the docker images to gcr.io/kubeflow-images-public      
  - app_dir: kubeflow/katib/test/workflows
    component: workflows-v1alpha1
    name: e2e-v1alpha1
    job_types:      
      - postsubmit
    include_dirs:
    - pkg/api/operators/apis/studyjob/*
    - pkg/api/operators/apis/*.go
    - pkg/api/health/*
    - pkg/api/v1alpha1/*
    - pkg/common/v1alpha1/*
    - pkg/controller/v1alpha1/*
    - pkg/db/v1alpha1/*
    - pkg/earlystopping/v1alpha1/*
    - pkg/manager/v1alpha1/*
    - pkg/manager/modelstore/*
    - pkg/suggestion/v1alpha1/*
    - pkg/ui/v1alpha1/*
    - cmd/earlystopping/medianstopping/v1alpha1/*
    - cmd/katib-controller/v1alpha1/*
    - cmd/manager/v1alpha1/*
    - cmd/manager-rest/v1alpha1/*
    - cmd/metricscollector/v1alpha1/*
    - cmd/suggestion/bayesianoptimization/v1alpha1/*
    - cmd/suggestion/grid/v1alpha1/*
    - cmd/suggestion/hyperband/v1alpha1/*
    - cmd/suggestion/nasenvelopenet/v1alpha1/*
    - cmd/suggestion/nasrl/v1alpha1/*
    - cmd/suggestion/random/v1alpha1/*
    - cmd/tfevent-metricscollector/v1alpha1/*
    - cmd/ui/v1alpha1/*
    - pkg/util/v1alpha1/*
    - test/scripts/v1alpha1/*
    - test/workflows/*
    - vendor/*
    params:
      registry: "gcr.io/kubeflow-images-public"
  - app_dir: kubeflow/katib/test/workflows
    component: workflows-v1alpha2
    name: e2e-v1alpha2
    job_types:
      - presubmit
    include_dirs:
    - pkg/api/operators/apis/common/v1alpha2/*
    - pkg/api/operators/apis/experiment/v1alpha2/*
    - pkg/api/operators/apis/trial/v1alpha2/*
    - pkg/api/operators/apis/*.go
    - pkg/api/health/*
    - pkg/api/v1alpha2/*
    - pkg/common/v1alpha2/*
    - pkg/controller/v1alpha2/*
    - pkg/db/v1alpha2/*
    - pkg/earlystopping/v1alpha2/*
    - pkg/manager/v1alpha2/*
    - pkg/manager/modelstore/*
    - pkg/suggestion/v1alpha2/*
    - pkg/ui/v1alpha2/*
    - cmd/earlystopping/medianstopping/v1alpha2/*
    - cmd/katib-controller/v1alpha2/*
    - cmd/manager/v1alpha2/*
    - cmd/manager-rest/v1alpha2/*
    - cmd/metricscollector/v1alpha2/*
    - cmd/suggestion/bayesianoptimization/v1alpha2/*
    - cmd/suggestion/grid/v1alpha2/*
    - cmd/suggestion/hyperband/v1alpha2/*
    - cmd/suggestion/nasenvelopenet/v1alpha2/*
    - cmd/suggestion/nasrl/v1alpha2/*
    - cmd/suggestion/random/v1alpha2/*
    - cmd/tfevent-metricscollector/v1alpha2/*
    - cmd/ui/v1alpha2/*
    - pkg/util/v1alpha2/*
    - test/e2e/v1alpha2/*
    - test/scripts/v1alpha2/*
    - test/workflows/*
    - manifests/v1alpha2/*
    - scripts/v1alpha2/*
    - vendor/*
    params:
      registry: "gcr.io/kubeflow-ci"
  - app_dir: kubeflow/katib/test/workflows
    component: workflows-v1alpha2
    name: e2e-v1alpha2
    job_types:
      - postsubmit
    include_dirs:
    - pkg/api/operators/apis/common/v1alpha2/*
    - pkg/api/operators/apis/experiment/v1alpha2/*
    - pkg/api/operators/apis/trial/v1alpha2/*
    - pkg/api/operators/apis/*.go
    - pkg/api/health/*
    - pkg/api/v1alpha2/*
    - pkg/common/v1alpha2/*
    - pkg/controller/v1alpha2/*
    - pkg/db/v1alpha2/*
    - pkg/earlystopping/v1alpha2/*
    - pkg/manager/v1alpha2/*
    - pkg/manager/modelstore/*
    - pkg/suggestion/v1alpha2/*
    - pkg/ui/v1alpha2/*
    - cmd/earlystopping/medianstopping/v1alpha2/*
    - cmd/katib-controller/v1alpha2/*
    - cmd/manager/v1alpha2/*
    - cmd/manager-rest/v1alpha2/*
    - cmd/metricscollector/v1alpha2/*
    - cmd/suggestion/bayesianoptimization/v1alpha2/*
    - cmd/suggestion/grid/v1alpha2/*
    - cmd/suggestion/hyperband/v1alpha2/*
    - cmd/suggestion/nasenvelopenet/v1alpha2/*
    - cmd/suggestion/nasrl/v1alpha2/*
    - cmd/suggestion/random/v1alpha2/*
    - cmd/tfevent-metricscollector/v1alpha2/*
    - cmd/ui/v1alpha2/*
    - pkg/util/v1alpha2/*
    - test/scripts/v1alpha2/*
    - test/workflows/*
    - vendor/*
    params:
      registry: "gcr.io/kubeflow-images-public"
