# This kustomization copies the `katib-standalone` one with following exclusions:
#  - No Job is spawned to generate TLS key for `katib-controller` Service
#  - Instead, the Service and WebhookConfigurations linked to it are annotated
#    for OpenShift service controller to handle TLS certification.
#  - PersistentVolume is not created, as OpenShift installations typically
#    have PVC dynamical provisioning configured or need some extra administrative
#    effort to provision a PV manually
#  - PersistentVolumeClaim has empty `.spec.storageClassName` to allow dynamic
#    provisioning with default StorageClass
#
#  Requires OpenShift version: 4.4+
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
  # Namespace.
  - ../../components/namespace/
  # Katib controller.
  - ../../components/controller/
  # Katib CRDs.
  - ../../components/crd/
  # Katib DB manager.
  - ../../components/db-manager/
  # Katib DB mysql.
  - ../../components/mysql/
  # Katib UI.
  - ../../components/ui/
  # Katib webhooks.
  - ../../components/webhook/
images:
  - name: docker.io/kubeflowkatib/katib-controller
    newName: docker.io/kubeflowkatib/katib-controller
    newTag: latest
  - name: docker.io/kubeflowkatib/katib-db-manager
    newName: docker.io/kubeflowkatib/katib-db-manager
    newTag: latest
  - name: docker.io/kubeflowkatib/katib-ui
    newName: docker.io/kubeflowkatib/katib-ui
    newTag: latest

patchesJson6902:
  # Annotate Service to delegate TLS-secret generation to OpenShift service controller
  # https://docs.openshift.com/container-platform/4.6/security/certificates/service-serving-certificate.html#add-service-certificate_service-serving-certificate
  - target:
      group: ""
      version: v1
      kind: Service
      name: katib-controller
    path: patch-service-serving-cert.yaml
  # Annotate WebhookConfigurations to delegate `caBundle` population to OpenShift service controller
  # https://docs.openshift.com/container-platform/4.6/security/certificates/service-serving-certificate.html#add-service-certificate-mutating-webhook_service-serving-certificate
  - target:
      group: admissionregistration.k8s.io
      version: v1
      kind: ValidatingWebhookConfiguration
      name: katib.kubeflow.org
    path: patch-webhook-inject-cabundle.yaml
  - target:
      group: admissionregistration.k8s.io
      version: v1
      kind: MutatingWebhookConfiguration
      name: katib.kubeflow.org
    path: patch-webhook-inject-cabundle.yaml
  # Remove PVC's storageClassName to provision it with the default StorageClass by default
  - target:
      group: ""
      version: v1
      kind: PersistentVolumeClaim
      name: katib-mysql
    path: patch-pvc-unset-storageClass.yaml
