apiVersion: v1
kind: ConfigMap
metadata:
  name: trial-template
  namespace: kubeflow
data:
  defaultTrialTemplate.yaml : |-
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: {{.WorkerID}}
      namespace: {{.NameSpace}}
    spec:
      template:
        spec:
          containers:
          - name: {{.WorkerID}}
            image: alpine
          restartPolicy: Never

