---
apiVersion: kubeflow.org/v1alpha3
kind: Experiment
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: xgb-svhn-fpga
  namespace: kubeflow
spec:
  algorithm:
    algorithmName: random
  maxFailedTrialCount: 3
  maxTrialCount: 10
  objective:
    additionalMetricNames:
      - time
    goal: 0.99
    objectiveMetricName: accuracy
    type: maximize
  parallelTrialCount: 1
  parameters:
    - feasibleSpace:
        min: "0.00"
        max: "0.05"
      name: alpha
      parameterType: double
    - feasibleSpace:
        min: "0.1"
        max: "0.4"
      name: eta
      parameterType: double
    - feasibleSpace:
        min: "0.6"
        max: "1.0"
      name: subsample
      parameterType: double
  trialTemplate:
    goTemplate:
      rawTemplate: |-
        apiVersion: batch/v1
        kind: Job
        metadata:
          name: {{.Trial}}
          namespace: {{.NameSpace}}
        spec:
          template:
            spec:
              containers:
                - name: {{.Trial}}
                  image: "docker.io/inaccel/jupyter:lab"
                  command:
                    - python3
                    - XGBoost/parameter-tuning.py
                  args:
                    - "--name=SVHN"
                    - "--test-size=0.35"
                    - "--tree-method=fpga_exact"
                    - "--bitstream=https://store.inaccel.com/artifactory/bitstreams/xilinx/aws-vu9p-f1/dynamic_5.0/com/inaccel/xgboost/0.1/2exact"
                    - "--max-depth=10"
                    {{- with .HyperParameters}}
                    {{- range .}}
                    - "--{{.Name}}={{.Value}}"
                    {{- end}}
                    {{- end}}
                  resources:
                    limits:
                      xilinx/aws-vu9p-f1: 1
              restartPolicy: Never
