apiVersion: v1
kind: Service
metadata:
  name: vizier-core-rest
  namespace: katib
  labels:
    app: vizier
    component: core-rest
spec:
#  type: ClusterIP
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      nodePort: 30678
      name: api
  selector:
    app: vizier
    component: core-rest
