apiVersion: v1
kind: Service
metadata:
  name: vizier-core-rest
  namespace: katib
  labels:
    app: vizier
    component: core-rest
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      name: api
  selector:
    app: vizier
    component: core-rest
