apiVersion: "kubeflow.org/v1alpha2"
kind: Experiment
metadata:
  namespace: kubeflow
  name: random-experiment
spec:
  parallelTrialCount: 3
  maxTrialCount: 12
  maxFailedTrialCount: 3
  objective:
    type: maximize
    goal: 0.99
    objectiveMetricName: Validation-accuracy
    additionalMetricNames:
      - accuracy
  algorithm:
    algorithmName: random
  metricsCollectorSpec:
    goTemplate:
      rawTemplate: |-
        apiVersion: batch/v1beta1
        kind: CronJob
        metadata:
          name: {{.Trial}}
          namespace: {{.NameSpace}}
        spec:
          schedule: "*/1 * * * *"
          successfulJobsHistoryLimit: 0
          failedJobsHistoryLimit: 1
          concurrencyPolicy: Forbid
          jobTemplate:
            spec:
              backoffLimit: 0
              template:
                spec:
                  serviceAccountName: metrics-collector
                  containers:
                  - name: {{.Trial}}
                    image: gcr.io/kubeflow-images-public/katib/v1alpha2/metrics-collector
                    imagePullPolicy: IfNotPresent
                    command: ["./metricscollector"]
                    args:
                    - "-e"
                    - "{{.Experiment}}"
                    - "-t"
                    - "{{.Trial}}"
                    - "-k"
                    - "{{.JobKind}}"
                    - "-n"
                    - "{{.NameSpace}}"
                    - "-m"
                    - "{{.ManagerService}}"
                    - "-mn"
                    - "{{.MetricNames}}"
                  restartPolicy: Never
  trialTemplate:
    goTemplate:
        rawTemplate: |-
          apiVersion: batch/v1
          kind: Job
          metadata:
            name: {{.Trial}}
            namespace: {{.NameSpace}}
          spec:
            template:
              spec:
                containers:
                - name: {{.Trial}}
                  image: katib/mxnet-mnist-example
                  command:
                  - "python"
                  - "/mxnet/example/image-classification/train_mnist.py"
                  - "--batch-size=64"
                  {{- with .HyperParameters}}
                  {{- range .}}
                  - "{{.Name}}={{.Value}}"
                  {{- end}}
                  {{- end}}
                restartPolicy: Never
  parameters:
    - name: --lr
      parameterType: double
      feasibleSpace:
        min: "0.01"
        max: "0.03"
    - name: --num-layers
      parameterType: int
      feasibleSpace:
        min: "2"
        max: "5"
    - name: --optimizer
      parameterType: categorical
      feasibleSpace:
        list:
        - sgd
        - adam
        - ftrl
