apiVersion: v1
kind: ConfigMap
metadata:
  name: katib-config
  namespace: kubeflow
data:
  metrics-collector-sidecar: |-
    {
      "StdOut": {
        "image": "gcr.io/kubeflow-images-public/katib/v1beta1/file-metrics-collector"
      },
      "File": {
        "image": "gcr.io/kubeflow-images-public/katib/v1beta1/file-metrics-collector"
      },
      "TensorFlowEvent": {
        "image": "gcr.io/kubeflow-images-public/katib/v1beta1/tfevent-metrics-collector",
        "resources": {
          "limits": {
            "memory": "1Gi"
          }
        }
      }
    }
  suggestion: |-
    {
      "random": {
        "image": "gcr.io/kubeflow-images-public/katib/v1beta1/suggestion-hyperopt"
      },
      "grid": {
        "image": "gcr.io/kubeflow-images-public/katib/v1beta1/suggestion-chocolate"
      },
      "hyperband": {
        "image": "gcr.io/kubeflow-images-public/katib/v1beta1/suggestion-hyperband"
      },
      "bayesianoptimization": {
        "image": "gcr.io/kubeflow-images-public/katib/v1beta1/suggestion-skopt"
      },
      "tpe": {
        "image": "gcr.io/kubeflow-images-public/katib/v1beta1/suggestion-hyperopt"
      },
      "enas": {
        "image": "gcr.io/kubeflow-images-public/katib/v1beta1/suggestion-enas",
        "imagePullPolicy": "Always",
        "resources": {
          "limits": {
            "memory": "200Mi"
          }
        }
      },
      "cmaes": {
        "image": "gcr.io/kubeflow-images-public/katib/v1beta1/suggestion-goptuna"
      },
      "darts": {
        "image": "gcr.io/kubeflow-images-public/katib/v1beta1/suggestion-darts"
      }
    }
  early-stopping: |-
    {
      "medianstop": {
        "image": "docker.io/andreyvelichkevich/earlystopping-median",
        "imagePullPolicy": "Always"
      }
    }
