apiVersion: v1
kind: Service
metadata:
  name: katib-ui
  namespace: katib
  labels:
    app: vizier
    component: ui
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      name: ui
  selector:
    app: vizier
    component: ui
