blank_issues_enabled: false

contact_links:
  - name: Katib Documentation
    url: https://www.kubeflow.org/docs/components/katib/
    about: Much help can be found in the docs
  - name: AutoML Slack Channel
    url: https://kubeflow.slack.com/archives/C018PMV53NW
    about: Ask the Katib community on Slack
