blank_issues_enabled: true

contact_links:
  - name: Katib Documentation
    url: https://www.kubeflow.org/docs/components/katib/
    about: Much help can be found in the docs
  - name: Kubeflow Katib Slack Channel
    url: https://cloud-native.slack.com/archives/C073N7AS48P
    about: Ask the Katib community on Slack
