# This is example with median stopping early stopping rule
apiVersion: "kubeflow.org/v1beta1"
kind: Experiment
metadata:
  namespace: kubeflow
  name: median-stop
spec:
  objective:
    type: maximize
    goal: 0.99
    objectiveMetricName: Validation-accuracy
    additionalMetricNames:
      - Train-accuracy
  algorithm:
    algorithmName: random
  earlyStopping:
    earlyStoppingAlgorithmName: medianstop
    earlyStoppingSettings:
      - name: min_samples_required
        value: "5"
  metricsCollectorSpec:
    collector:
      kind: StdOut
    source:
      filter:
        metricsFormat:
          - ([\w|-]+)\s*=\s*((-?\d+)(\.\d+)?)
          - (\w+)\[(\d+)
  parallelTrialCount: 2
  maxTrialCount: 15
  maxFailedTrialCount: 3
  parameters:
    - name: lr
      parameterType: double
      feasibleSpace:
        min: "0.01"
        max: "0.03"
    - name: num-epochs
      parameterType: int
      feasibleSpace:
        min: "8"
        max: "10"
  trialTemplate:
    retain: true
    primaryPodLabels:
      "pod-role": "primary"
    primaryContainerName: training-container
    successCondition: status.conditions.#(type=="Complete")#|#(status=="True")#
    failureCondition: status.conditions.#(type=="Failed")#|#(status=="True")#
    trialParameters:
      - name: learningRate
        description: Learning rate for the training model
        reference: lr
      - name: numEpochs
        description: Learning rate for the training model
        reference: num-epochs
    trialSpec:
      apiVersion: batch/v1
      kind: Job
      spec:
        template:
          metadata:
            labels:
              "pod-role": "primary"
          spec:
            containers:
              - name: training-container
                image: docker.io/kubeflowkatib/mxnet-mnist
                command:
                  - "python3"
                  - "/opt/mxnet-mnist/mnist.py"
                  - "--batch-size=64"
                  - "--lr=${trialParameters.learningRate}"
                  - "--num-epochs=${trialParameters.numEpochs}"
            restartPolicy: Never
