apiVersion: batch/v1
kind: Job
metadata:
  name: katib-cert-generator
  namespace: kubeflow
  labels:
    katib.kubeflow.org/component: cert-generator
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: katib-cert-generator
      securityContext:
        runAsNonRoot: true
      containers:
        - name: cert-generator
          image: docker.io/kubeflowkatib/cert-generator
          imagePullPolicy: Always
          command: ["./katib-cert-generator"]
          args: ["generate", "--namespace=$(KATIB_CORE_NAMESPACE)"]
          env:
            - name: KATIB_CORE_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          securityContext:
            allowPrivilegeEscalation: false
      restartPolicy: Never
  backoffLimit: 4
