apiVersion: "kubeflow.org/v1alpha1"
kind: StudyJob
metadata:
  namespace: katib
  labels:
    controller-tools.k8s.io: "1.0"
  name: gpu-example
spec:
  studySpec:
      name: gpu-example
      owner: crd
      optimizationtype: maximize
      objectivevaluename: Validation-accuracy
      optimizationgoal: 0.99
      metricsnames:
        - accuracy
      parameterconfigs:
        - name: --lr
          parametertype: double
          feasible:
            min: "0.01"
            max: "0.03"
        - name: --num-layers
          parametertype: int
          feasible:
            min: "2"
            max: "3"
        - name: --optimizer
          parametertype: categorical
          feasible:
            list:
            - sgd
            - adam
            - ftrl
  workerSpec:
    workerType: "Default"
    image: "katib/mxnet-mnist-example"
    workerTemplatePath: "/worker-template/gpuWorkerTemplate.yaml"
    workerParameters:
        Gpu: "1"
    command: 
        - "python"
        - "/mxnet/example/image-classification/train_mnist.py"
        - "--batch-size=64"
  suggestionSpec:
    suggestionAlgorithm: "random"
    requestNumber: 3
