apiVersion: "kubeflow.org/v1alpha1"
kind: StudyJob
metadata:
  namespace: kubeflow
  labels:
    controller-tools.k8s.io: "1.0"
  name: grid-example
spec:
  studyName: grid-example
  owner: crd
  optimizationType: maximize
  objectiveValueName: Validation-accuracy
  optimizationGoal: 0.99
  metricsNames:
    - accuracy
  parameterConfigs:
    - name: --lr
      parameterType: double
      feasible:
        min: "0.01"
        max: "0.03"
    - name: --num-layers
      parameterType: int
      feasible:
        min: "2"
        max: "5"
    - name: --optimizer
      parameterType: categorical
      feasible:
        list:
        - sgd
        - adam
        - ftrl
  workerSpec:
    goTemplate:
        templatePath: "/worker-template/cpuWorkerTemplate.yaml"
  suggestionSpec:
    suggestionAlgorithm: "grid"
    suggestionParameters:
      - 
          name: "DefaultGrid"
          value: "1"
      - 
          name: "--lr"
          value: "4"
