apiVersion: "kubeflow.org/v1alpha1"
kind: StudyJob
metadata:
  namespace: kubeflow
  labels:
    controller-tools.k8s.io: "1.0"
  name: nas-reinfocement-learning-example
spec:
  studyName: nas-reinfocement-learning-example
  owner: crd
  optimizationtype: maximize
  objectivevaluename: Validation-accuracy
  optimizationgoal: 0.99
  metricsnames:
    - accuracy
  graphConfig:
    numVertex: 8
    inputSize:
      - 32
      - 32
      - 3
    outputSize:
      - 10
  operations:
    - operationType: "convolution"
      parameterconfigs:
        - name: "filter_size"
          parametertype: categorical
          feasible:
            list:
            - 3
            - 5
            - 7
        - name: "num_filter"
          parametertype: categorical
          feasible:
            list:
            - 32
            - 48
            - 64
            - 96
            - 128
        - name: "stride"
          parametertype: categorical
          feasible:
            list:
            - 1
            - 2
        - name: "activation"
          parametertype: categorical
          fesible:
            list:
            - relu
            - sigmoid
            - tanh
            - identity
    - operationType: "reduction"
      parameterconfigs:
        - name: "reduction_type"
          parametertype: categorical
          feasible:
            list:
            - 'maxpooling'
            - 'avgpooling'
        - name: "pool_size"
          parametertype: int
          feasible:
            min: 1
            max: 3
        - name: "stride"
          parametertype: categorical
          feasible:
            list:
            - 1
            - 2
    - operationType: "dense"
      parameterconfigs:
        - name: "num_units"
          parametertype: categorical
          feasible:
            list:
              - 128
              - 256
              - 512
              - 1024
        - name: "activation"
          parametertype: categorical
          fesible:
            list:
            - relu
            - sigmoid
            - tanh
            - identity
        - name: "dropout_rate"
          parametertype: range
          feasible:
            min: 0.2
            max: 0.5
            step: 0.1
  workerSpec:
    goTemplate:
        rawTemplate: |-
          apiVersion: batch/v1
          kind: Job
          metadata:
            name: {{.WorkerID}}
            namespace: kubeflow
          spec:
            template:
              spec:
                imagePullSecrets:
                  - name: gitlabregcred
                containers:
                - name: {{.WorkerID}}
                  image: katib/mxnet-mnist-example
                  command:
                  - "python"
                  - "/mxnet/example/image-classification/train_mnist.py"
                  - "--batch-size=32"
                  {{- with .HyperParameters}}
                  {{- range .}}
                  - "{{.Name}}={{.Value}}"
                  {{- end}}
                  {{- end}}
                restartPolicy: Never
  suggestionSpec:
    suggestionAlgorithm: "reinforcement-learning"
    suggestionParameters:
      - name: "num_control_cells"
        value: "32"
      - name: "embedding_dim"
        value: "20"
      - name: "accuracy_beta"
        value: "0.8"
      - name: "clip_rewards"
        value: "0"
      - name: "embedding_dim"
        value: "20"
      - name: "discount_factor"
        value: "0.95"
