---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
  # Namespace.
  - ../../components/namespace/
  # Katib controller.
  - ../../components/controller/
  # Katib CRDs.
  - ../../components/crd/
  # Katib DB manager.
  - ../../components/db-manager/
  # Katib DB postgres.
  - ../../components/postgres/
  # Katib UI.
  - ../../components/ui/
  # Katib Cert Generator
  - ../../components/cert-generator/
  # Katib webhooks.
  - ../../components/webhook/
images:
  - name: docker.io/kubeflowkatib/katib-controller
    newName: docker.io/kubeflowkatib/katib-controller
    newTag: e2e-test
  - name: docker.io/kubeflowkatib/katib-db-manager
    newName: cr.makina.rocks/library/katib-db-manager # TODO need to change it to official katib image
    newTag: e2e-test
  - name: docker.io/kubeflowkatib/katib-ui
    newName: docker.io/kubeflowkatib/katib-ui
    newTag: e2e-test
  - name: docker.io/kubeflowkatib/cert-generator
    newName: docker.io/kubeflowkatib/cert-generator
    newTag: e2e-test
patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env
        value:
          - name: DB_NAME
            value: "postgres"
          - name: DB_PASSWORD
            value: "katib"
    target:
      kind: Deployment
      labelSelector: "katib.kubeflow.org/component=db-manager"

