# Composite action to setup e2e tests.
name: Setup E2E Test
description: setup env for e2e test using the minikube cluster

inputs:
  kubernetes-version:
    required: true
    description: kubernetes version

runs:
  using: composite
  steps:
    - name: Set Up Minikube Cluster
      uses: manusa/actions-setup-minikube@v2.6.0
      with:
        minikube version: "v1.25.2"
        kubernetes version: ${{ inputs.kubernetes-version }}
        start args: --driver none --wait-timeout=60s
        github token: ${{ env.GITHUB_TOKEN }}

    - name: Set Up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set Up Go env
      uses: actions/setup-go@v3
      with:
        go-version-file: go.mod
