# Composite action to setup e2e tests.
name: Setup E2E Test
description: setup env for e2e test using the minikube cluster

inputs:
  kubernetes-version:
    required: true
    description: kubernetes version
  python-version:
    required: false
    description: Python version
    # Most latest supporting version
    default: "3.10"

runs:
  using: composite
  steps:
    - name: Setup Minikube Cluster
      uses: manusa/actions-setup-minikube@v2.7.2
      with:
        minikube version: v1.28.0
        kubernetes version: ${{ inputs.kubernetes-version }}
        start args: --wait-timeout=60s
        driver: none
        github token: ${{ env.GITHUB_TOKEN }}

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Katib SDK
      shell: bash
      run: pip install --prefer-binary -e sdk/python/v1beta1
