apiVersion: v1
kind: Service
metadata:
  name: katib-manager
  namespace: kubeflow
  labels:
    app: katib
    component: manager
spec:
  type: NodePort
  ports:
    - port: 6789
      protocol: TCP
      nodePort: 30678
      name: api
  selector:
    app: katib
    component: manager
