apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vizier-suggestion-grid
  namespace: kubeflow
  labels:
    app: vizier
    component: suggestion-grid
spec:
  replicas: 1
  template:
    metadata:
      name: vizier-suggestion-grid
      labels:
        app: vizier
        component: suggestion-grid
    spec:
      containers:
      - name: vizier-suggestion-grid
        image: gcr.io/kubeflow-images-public/katib/v1alpha1/suggestion-grid
        ports:
        - name: api
          containerPort: 6789
