apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
  # Namespace.
  - namespace.yaml
  # Katib controller.
  - ../../components/controller/
  # Katib CRDs.
  - ../../components/crd/
  # Katib DB manager.
  - ../../components/db-manager/
  # Katib DB mysql.
  - ../../components/mysql/
  # Katib UI.
  - ../../components/ui/
  # Katib webhooks.
  - ../../components/webhook/
images:
  - name: docker.io/kubeflowkatib/katib-controller
    newTag: v0.11.0
    newName: docker.io/kubeflowkatib/katib-controller
  - name: docker.io/kubeflowkatib/katib-db-manager
    newTag: v0.11.0
    newName: docker.io/kubeflowkatib/katib-db-manager
  - name: docker.io/kubeflowkatib/katib-ui
    newTag: v0.11.0
    newName: docker.io/kubeflowkatib/katib-ui
  - name: docker.io/kubeflowkatib/cert-generator
    newTag: v0.11.0
    newName: docker.io/kubeflowkatib/cert-generator
patchesStrategicMerge:
  - katib-config-patch.yaml
