apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
  # Katib controller.
  - ../../components/controller/
  # Katib CRDs.
  - ../../components/crd/
  # Katib DB manager.
  - ../../components/db-manager/
  # Katib DB mysql.
  - ../../components/mysql/
  # Katib UI.
  - ../../components/ui/
  # Katib webhooks.
  - ../../components/webhook/
  # Cert-manager certificate for webhooks
  - certificate.yaml
  # Kubeflow Katib components.
  - kubeflow-katib-roles.yaml
  - ui-virtual-service.yaml
images:
  - name: docker.io/kubeflowkatib/katib-controller
    newTag: latest
    newName: docker.io/kubeflowkatib/katib-controller
  - name: docker.io/kubeflowkatib/katib-db-manager
    newTag: latest
    newName: docker.io/kubeflowkatib/katib-db-manager
  - name: docker.io/kubeflowkatib/katib-ui
    newTag: latest
    newName: docker.io/kubeflowkatib/katib-ui
  - name: docker.io/kubeflowkatib/cert-generator
    newTag: latest
    newName: docker.io/kubeflowkatib/cert-generator

patchesStrategicMerge:
  - katib-config-patch.yaml
  - remove-pv-patch.yaml
  - patches/katib-cert-injection.yaml

patchesJson6902:
  - path: patches/mysql-pvc.yaml
    target:
      version: v1
      name: katib-mysql
      kind: PersistentVolumeClaim
      namespace: kubeflow

vars:
- fieldref:
    fieldPath: metadata.namespace
  name: KATIB_UI_NAMESPACE
  objref:
    apiVersion: apps/v1
    kind: Deployment
    name: katib-ui
- fieldref:
    fieldPath: metadata.namespace
  name: KATIB_NAMESPACE
  objref:
    apiVersion: v1
    kind: Service
    name: katib-controller
- fieldref:
    fieldPath: metadata.name
  name: KATIB_SERVICE_NAME
  objref:
    apiVersion: v1
    kind: Service
    name: katib-controller
- name: KATIB_CERT_NAME
  objref:
      kind: Certificate
      group: cert-manager.io
      version: v1alpha2
      name: katib-webhook-cert
  fieldref:
    fieldpath: metadata.name

configurations:
  - params.yaml
