apiVersion: v1
kind: Service
metadata:
  name: katib-suggestion-random
  namespace: kubeflow
  labels:
    app: katib
    component: suggestion-random
spec:
  type: ClusterIP
  ports:
    - port: 6789
      protocol: TCP
      name: api
  selector:
    app: katib
    component: suggestion-random
