apiVersion: v1
kind: Service
metadata:
  name: modeldb-frontend
  namespace: katib
  labels:
    app: modeldb
    component: frontend
spec:
  type: NodePort
  ports:
    - port: 3000
      protocol: TCP
      name: ui
      nodePort: 30080
  selector:
    app: modeldb
    component: frontend
