apiVersion: apps/v1
kind: Deployment
metadata:
  name: katib-suggestion-nasrl
  namespace: kubeflow
  labels:
    app: katib
    component: suggestion-nasrl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: katib
      component: suggestion-nasrl
  template:
    metadata:
      name: katib-suggestion-nasrl
      labels:
        app: katib
        component: suggestion-nasrl
    spec:
      containers:
      - name: katib-suggestion-nasrl
        image: gcr.io/kubeflow-images-public/katib/v1alpha2/suggestion-nasrl
        ports:
        - name: api
          containerPort: 6789
