name: Lint YAML files

on:
  - push
  - pull_request

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          set -eux
          sudo apt update
          sudo apt install python3-setuptools
          sudo pip3 install yamllint

      - name: Check YAML
        run: |
          yamllint -d "{extends: default, rules: {line-length: disable}}" examples/* manifests/*
