name: E2E Test With mxnet-mnist Image
on:
  - push
  - pull_request

jobs:
  e2e:
    runs-on: ubuntu-20.04
    timeout-minutes: 120
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Test Env
        uses: ./.github/workflows/template-setup-e2e-test
        with:
          kubernetes-version: ${{ matrix.kubernetes-version }}

      - name: Run e2e test with ${{ matrix.experiments }} experiments
        uses: ./.github/workflows/template-e2e-test
        with:
          experiments: ${{ matrix.experiments }}
          # Comma Delimited
          trial-images: mxnet-mnist

    strategy:
      fail-fast: false
      matrix:
        # Detail: https://hub.docker.com/r/kindest/node
        kubernetes-version: ["v1.21.12", "v1.22.9", "v1.23.6", "v1.24.1"]
        # Comma Delimited
        experiments:
          # suggestion-hyperopt
          - "random,tpe,never-resume,from-volume-resume,median-stop"
          # others
          - "grid,bayesian-optimization,tpe"
          - "multivariate-tpe,cma-es,hyperband"
