name: Publish AutoML Algorithm Images

on:
  push:
    branches:
      - master

jobs:
  # Suggestion Images.
  suggestion-hyperopt:
    name: Suggestion Hyperopt
    uses: kubeflow/katib/.github/workflows/publish-image-template.yaml@master
    with:
      image: docker.io/kubeflowkatib/suggestion-hyperopt
      dockerfile: cmd/suggestion/hyperopt/v1beta1/Dockerfile
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

  suggestion-chocolate:
    name: Suggestion Chocolate
    uses: kubeflow/katib/.github/workflows/publish-image-template.yaml@master
    with:
      image: docker.io/kubeflowkatib/suggestion-chocolate
      dockerfile: cmd/suggestion/chocolate/v1beta1/Dockerfile
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

  suggestion-hyperband:
    name: Suggestion Hyperband
    uses: kubeflow/katib/.github/workflows/publish-image-template.yaml@master
    with:
      image: docker.io/kubeflowkatib/suggestion-hyperband
      dockerfile: cmd/suggestion/hyperband/v1beta1/Dockerfile
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

  suggestion-skopt:
    name: Suggestion Skopt
    uses: kubeflow/katib/.github/workflows/publish-image-template.yaml@master
    with:
      image: docker.io/kubeflowkatib/suggestion-skopt
      dockerfile: cmd/suggestion/skopt/v1beta1/Dockerfile
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

  suggestion-goptuna:
    name: Suggestion Goptuna
    uses: kubeflow/katib/.github/workflows/publish-image-template.yaml@master
    with:
      image: docker.io/kubeflowkatib/suggestion-goptuna
      dockerfile: cmd/suggestion/goptuna/v1beta1/Dockerfile
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

  suggestion-optuna:
    name: Suggestion Optuna
    uses: kubeflow/katib/.github/workflows/publish-image-template.yaml@master
    with:
      image: docker.io/kubeflowkatib/suggestion-optuna
      dockerfile: cmd/suggestion/optuna/v1beta1/Dockerfile
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

  suggestion-enas:
    name: Suggestion ENAS
    uses: kubeflow/katib/.github/workflows/publish-image-template.yaml@master
    with:
      image: docker.io/kubeflowkatib/suggestion-enas
      dockerfile: cmd/suggestion/nas/enas/v1beta1/Dockerfile
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

  suggestion-darts:
    name: Suggestion DARTS
    uses: kubeflow/katib/.github/workflows/publish-image-template.yaml@master
    with:
      image: docker.io/kubeflowkatib/suggestion-darts
      dockerfile: cmd/suggestion/nas/darts/v1beta1/Dockerfile
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

  # Early Stopping Images.
  earlystopping-medianstop:
    name: Early Stopping MedianStop
    uses: kubeflow/katib/.github/workflows/publish-image-template.yaml@master
    with:
      image: docker.io/kubeflowkatib/earlystopping-medianstop
      dockerfile: cmd/earlystopping/medianstop/v1beta1/Dockerfile
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
