name: E2E Test With pytorch-mnist Trial Image
on:
  - push
  - pull_request

jobs:
  e2e:
    runs-on: ubuntu-20.04
    timeout-minutes: 120
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Test Env
        uses: ./.github/workflows/template-setup-e2e-test
        with:
          kubernetes-version: ${{ matrix.kubernetes-version }}

      - name: Run e2e test with ${{ matrix.experiments }} experiments
        uses: ./.github/workflows/template-e2e-test
        with:
          experiments-path: ${{ matrix.experiments }}
          training-operator: true
          # Comma Delimited
          trial-images: pytorch-mnist

    strategy:
      fail-fast: false
      matrix:
        # Detail: https://hub.docker.com/r/kindest/node
        kubernetes-version: ["v1.21.12", "v1.22.9", "v1.23.6", "v1.24.1"]
        # Comma Delimited
        # We must run experiments individually as they take a long time.
        experiments:
          - "file-metrics-collector"
          - "pytorchjob-mnist"
          - "file-metrics-collector-with-json-format"
          - "median-stop-with-json-format"
