name: Python Test

on:
  pull_request:
    paths-ignore:
      - "pkg/ui/v1beta1/frontend/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install Katib SDK
        shell: bash
        run: pip install --prefer-binary -e sdk/python/v1beta1
          
      - name: Install Training Operator SDK
        shell: bash
        run: |
          pip install git+https://github.com/kubeflow/training-operator.git@v1.8-branch#subdirectory=sdk/python
          pip install peft==0.3.0 datasets==2.15.0 transformers==4.38.0

      - name: Run Python test
        run: make pytest

  # The skopt service doesn't work appropriately with Python 3.11.
  # So, we need to run the test with Python 3.9.
  # TODO (tenzen-y): Once we stop to support skopt, we can remove this test.
  # REF: https://github.com/kubeflow/katib/issues/2280
  test-skopt:
    name: Test Skopt
    runs-on: ubuntu-22.04

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Run Python test
        run: make pytest-skopt
