name: Go Test

on:
  - push
  - pull_request

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go 1.15.8
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.8
        env:
          GOPATH: /home/runner/go

      - name: Run Go check
        run: make check

      - name: Run Go test
        run: make test

      - name: Create Coveralls Report
        run: goveralls -coverprofile=coverage.out
