name: Go Test

on:
  - push
  - pull_request

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      GOPATH: ${{ github.workspace }}
    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          path: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}

      - name: Set up Go 1.15.8
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.8

      - name: Run Go test
        run: |
          echo $GOPATH
          ls -A
          ls -A hack/
          ls -a hack/boilerplate/
          pwd
          go mod download
          make check
          make test
          goveralls -coverprofile=coverage.out
