name: Go Test

on:
  - push
  - pull_request

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      GOPATH: ${{ github.workspace }}/go
    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/src/github.com/kubeflow/katib

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          path: ${{ env.GOPATH }}/src/github.com/kubeflow/katib

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.1

      # Verify that go.mod and go.sum is synchronized
      - name: Check Go modules
        run: |
          if [[ ! -z $(go mod tidy && git diff --exit-code) ]]; then
            echo "Please run "go mod tidy" to sync Go modules"
            exit 1
          fi

      - name: Run Go test
        run: |
          go mod download
          make check
          make test

      - name: Coveralls report
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: coverage.out
          working-directory: ${{ env.GOPATH }}/src/github.com/kubeflow/katib
