name: Shellcheck

on:
  push:
    paths-ignore:
      - 'pkg/new-ui/v1beta1/frontend/**'
  pull_request:
    paths-ignore:
      - 'pkg/new-ui/v1beta1/frontend/**'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run shellcheck
        run: make shellcheck
